spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format.sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
